### PR TITLE
SE-3475: adds terraform modules for simple OpenedX resources setup

### PR DESCRIPTION
**Pull request by eLRuLL**
This merge request is about adding the configured (and currently used) terraform modules from UBC to this repo so they can be used and versioned into other projects that need AWS deployment

**Jira tickets**

- [SE-3475](https://tasks.opencraft.com/browse/SE-3575)

**Author's notes and concerns**
I copied them from UBC and checked them again, adding a readme into each of the modules. At least I'd like to merge this version as it is (we can improve the READMEs of course) and then improve on them if some resources need to be modified, as I need to also change UBC to point to these modules.

Still, if you think that some resources or anything needs more explaining, please let me know

**Reviewers**

- [ ] @pomegranited 
- [ ] @swalladge

### CODE REVIEW

**Comment by giovannicimolin** [comment]
@eLRuLL Awesome to see this repo moving forward and getting more support!
Is there a way we can squash down the extra modules down to a single `.tf` file per service set up? 

I think that creating this many modules can make the code unnecessarily complex. If I remember correctly, this was one of @bradenmacdonald's comments about the current implementation.

**Edit:** It's ok if we don't have budget to leave as is if it doesn't break other deployments. This is versioned anyway, but managing conflicts between changes might become cumbersome to client with particular requirements (like ones using AWS regions without supported services).

**Comment by eLRuLL** [comment]
@giovannicimolin I think we should take care of the improvements in future tickets, the one involving this migration is actually just to "document" terraform deployment, for which I think this is a good step (we are just moving away the current implemented modules for UBC)

I think the idea of future client deployments, should always come with improvements here, and the ones being managed already should stick to their versions, unless we really need an upgrade (I don't think it's very common), this also makes it easier for stage/prod infrastructure differentiation

**Review by samuelallan72 — APPROVED** [review]
@eLRuLL :+1:

Note that this isn't fully tested, but I think it's fine since this is simply a first effort to document and standardize the process. We can iterate on the scripts and docs when we next do an AWS deployment.

One small nit perhaps: could you add some more info to the root readme about the new modules, and how they differ from the files already in the repo?

- [x] I tested this: read through the code and accomanying private docs
- [x] I read through the code
- [ ] NA I checked for accessibility issues
- [x] Includes documentation

**Comment by eLRuLL** [comment]
@swalladge thank you @swalladge I added more information to the README so we can understand this project better

**Comment by giovannicimolin** [comment]
@eLRuLL Can you create a new release and add a small description of the changes to it? It'll help you keep track of this repo's versions.

**Comment by bradenmacdonald** [comment]
@eLRuLL  @giovannicimolin @swalladge 

> One small nit perhaps: could you add some more info to the root readme about the new modules, and how they differ from the files already in the repo?

I see that the README now says "First approach" and "Second approach" , but it doesn't explain a plan for unifying those, or state which one should be used for new deployments. Can we pick which approach we prefer, and indicate that, eventually replacing the other approach so there's only one?

**Comment by eLRuLL** [comment]
that's the idea but I guess we'll need a little discussing and/or me checking @giovannicimolin 's implementation (or the other way around) to decide how it would be better to unify things. I am sorry if I am complicating things at the beginning at least, but I just didn't want to go over the budget for my previous task

**Comment by eLRuLL** [comment]
> @eLRuLL Can you create a new release and add a small description of the changes to it? It'll help you keep track of this repo's versions.

definitely, doing that now

**Pull request merged**
