### PR TITLE
[BB-3505] - Add memcached `engine version` parameter

### PR DESCRIPTION
**Pull request by Agrendalath**
Deploying the memcached cluster by specifying its `parameter group` results in the `CacheParameterGroupNotFound` error.

### CODE REVIEW

**Comment by lgp171188** [comment]
@Agrendalath, you might want to use the changes merged via https://github.com/open-craft/terraform-scripts/pull/4 for your task.

> Deploying the memcached cluster by specifying its parameter group results in the CacheParameterGroupNotFound error.

Which version of Terraform are you using? I used 0.12.x as recommended by @giovannicimolin and didn't run into this error when I set up NELP stage last weekend.

**Comment by Agrendalath** [comment]
@lgp171188, thank you for checking. As you can see, I used the branch from #4 as a base for this PR. Unfortunately that approach didn't fix this issue.

I'm running v0.12.29 and I'm not sure what has changed since then - maybe the default `engine version`'s value in AWS is now 1.6.x instead of 1.5.x? The proposed approach has fixed the issue for me.

**Comment by lgp171188** [comment]
@Agrendalath, I tried running these scripts (the `main` branch version, not this PR's) in `me-south-1` and terraform complained about `memcached1.5` being unavailable and I had to set

```
memcached_parameter_group_name = "default.memcached1.6"
```
in `application.tf` to get it to use Memcached 1.6 and stop erroring out.

**Comment by Agrendalath** [comment]
@lgp171188, I have used this in `us-east-1`, and this region has three parameter groups: 1.4, 1.5 and 1.6.
The instance I'm spawning runs on `ginkgo.1`, so I went with 1.4 for the compatibility reasons.

**Comment by Agrendalath** [comment]
Update: I just tried updating the cluster version with the `main` branch, but it returned the following error:
`Error updating ElastiCache cluster (XXX-memcached-stage), error: InvalidParameterValue: The parameter CacheParameterGroupName is not a valid identifier. Identifiers must begin with a letter; must contain only ASCII letters, digits, and hyphens; and must not end with a hyphen or contain two consecutive hyphens.
status code: 400,`

I looked again at the output of `plan` and shows that the `parameter_group_name` is indeed being updated, but the `engine_version` stays the same. It might be a bug in Terraform (or at least `v0.12.29`).
```
engine_version           = "1.4.34"
...
~ parameter_group_name     = "default.memcached1.4" -> "default.memcached1.5"
```

**Comment by giovannicimolin** [comment]
@Agrendalath Turns out this started happening in NELC's deployment too, though we still need the older variable.
This is because the default memcached instance in the **me** region was 1.5, so no issues when we initially implemented it, but now the default is Memcached 1.6, which breaks the deployment. 
Didn't think of that while I did the first review pass.  

I'll push a change here to just add instead of replace the variable.
Note that'll add default values to memcached `1.5.16`, for ginkgo you'll need to override it.

@lgp171188 Can you review this as part of BB-3505?

**Comment by lgp171188** [comment]
@giovannicimolin, I checked the commit in question and it looks good to me. 👍🏼 I can see that this worked for the recent production deployment for NELC.

**Pull request merged**
